### ISSUE TITLE
Todos: 2016-10-13

### ISSUE THREAD

**Issue by jaredscheib** [liquidvote/org#11]
- [x] Submit materials to Crowdpac
- [ ] Add email call-to-action to blog https://github.com/liquidvote/blog/issues/17
- [ ] Expand the sharing buttons and clarity on blog
- [ ] Add kudos to blog
- [ ] Add better context etc. to demo
- [ ] Approve at least 1 new blog post
- [ ] Get real-world example for crowdfunding campaign
- [ ] Improve contributor instructions for setting up dev environments
- [ ] Debate doing the whole app as a webapp in native browser views

**Comment by dsernst** [comment]
Closing since this date passed. I believe most of these are their own issues or PRs already
